create database retail;
use retail;

alter table  retail.orders
add constraint fk_stocks_store_id
foreign key (store_id)
references stores(store_id)
on delete restrict
on update cascade;

alter table  retail.stocks
add constraint fk_stocks_product_id
foreign key (product_id)
references products(product_id)
on delete restrict
on update cascade;

select * from retail.brands;
select * from retail.categories;
select * from retail.customers;
select * from retail.order_items;
select * from retail.orders;
select * from retail.products;
select * from retail.staffs;
select * from retail.stocks;
select * from retail.stores;


-- question no : 3 Join orders, order_items, and products to display detailed line items.
select orders.order_id,orders.order_date,orders.customer_id,products.product_id,products.product_name,
order_items.quantity,order_items.total_price,order_items.discount from orders join order_items on 
orders.order_id=order_items.order_id join products on order_items.product_id=products.product_id
order by orders.order_id,products.product_name;

-- question no : 4 Write a query to group sales (total_price) by each store_id.
select orders.store_id,stores.store_name,
sum(order_items.quantity*order_items.list_price*(1-order_items.discount))
as total_sales from orders join order_items on orders.order_id=order_items.order_id 
join stores on orders.store_id=stores.store_id
group by orders.store_id,stores.store_name;

-- question no : 5 Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.
select product_id,sum(quantity) as total_quantity from retail.order_items
group by product_id order by total_quantity desc limit 5;

-- question no : 6 For each customer, return total orders placed, total items purchased and total revenue.


select customers.customer_id,customers.first_name as customer_name,count(distinct orders.order_id) as total_order,
sum(order_items.quantity) as total_qty,
sum(order_items.quantity*order_items.list_price*(1-order_items.discount)) as total_sales from customers
join orders on customers.customer_id=orders.customer_id
join order_items on orders.order_id=order_items.order_id group by customers.customer_id,first_name
order by  total_sales desc;


-- question no :7 Write a query to classify customers into spending brackets (e.g., low, medium, high).


select customers.customer_id,customers.first_name as customer_name,count(distinct orders.order_id) as total_order,
sum(order_items.quantity*order_items.list_price*(1-order_items.discount)) as total_spent ,
case 
when sum(order_items.quantity*order_items.list_price*(1-order_items.discount))<5000
then 'low' when sum(order_items.quantity*order_items.list_price*(1-order_items.discount)) between 5000 and 15000
then ' mid' else 'high' end as spending_brackets from customers 
join orders on customers.customer_id = orders.customer_id 
join order_items on orders.order_id = order_items.order_id 
group by customer_id,customer_name order by total_spent desc;

-- question no :8 Analyze total revenue generated by each staff member based on their handled orders.

select orders.order_id,staffs.staff_id,sum((order_items.total_price)) as total_revenue from  orders
join staffs on orders.staff_id=staffs.staff_id
join order_items on orders.order_id = order_items.order_id
group by staff_id,order_id order by total_revenue desc;

-- question no :9 Write a query to list products where stock quantity < 10 in any store.

select products.product_id,products.product_name,sum(stocks.quantity)  from products 
join stocks on products.product_id = stocks.quantity 
where quantity  < 10 group by product_id;

-- question no :10 Create a table customer_segments that will be populated from Python ML results later.
create table customer_segment(
customer_id int,
recency int,
frequency int,
Monetary int);
select * from retail.customer_segment;



-- python 

select orders.staff_id,sum(order_items.total_price) as total_pricee from orders 
join order_items on orders.order_id=order_items.order_id 
join staffs on orders.staff_id=staffs.staff_id  
group by orders.staff_id order by orders.staff_id;
 
 

-- python 

select customers.customer_id, customers.state,sum(order_items.total_price) as total_pricee from orders 
join customers on orders.customer_id=customers.customer_id 
join order_items on orders.order_id=order_items.order_id  
group by customer_id order by total_pricee;


-- Recency: Days since last order
select customers.customer_id,datediff(curdate(),max(orders.order_date))as recency from orders 
join customers on orders.customer_id=customers.customer_id 
join order_items on orders.order_id=order_items.order_id  
group by customer_id;

-- Frequency: Number of orders
select customers.customer_id,count(orders.order_id) as frequency  from orders 
join customers on orders.customer_id=customers.customer_id 
join order_items on orders.order_id=order_items.order_id  
group by customer_id;


--  Monetary
select customers.customer_id,sum(order_items.total_price) as frequency  from orders 
join customers on orders.customer_id=customers.customer_id 
join order_items on orders.order_id=order_items.order_id  
group by customer_id;




select customers.customer_id,datediff(curdate(),max(orders.order_date)) as recency,count(order_items.total_price) as frequency,
sum(order_items.total_price) as Monetary from orders 
join customers on orders.customer_id=customers.customer_id 
join order_items on orders.order_id=order_items.order_id  
group by customer_id;



SET SQL_SAFE_UPDATES = 0;


UPDATE orders
SET order_date = STR_TO_DATE(order_date, '%m/%d/%Y');


UPDATE orders
SET order_date = STR_TO_DATE(order_date, '%m/%d/%Y')
WHERE order_date LIKE '%/%/%';

select * from retail.customer_segment;


use retail;

alter table  retail.orders
add constraint fk_orders_staff_id
foreign key (staff_id)
references staffs(staff_id)
on delete restrict
on update cascade;










